name: gpv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py36h9f0ad1d_0
  - cloudpickle=1.5.0=py_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py36h516909a_0
  - dask-core=2.21.0=py_0
  - decorator=4.4.2=py_0
  - enum34=1.1.10=py36h9f0ad1d_1
  - freetype=2.10.2=h5ab3b9f_0
  - imagecodecs-lite=2019.12.3=py36h785e9b2_1
  - imageio=2.9.0=py_0
  - intel-openmp=2020.1=217
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.2.0=py36hdb11119_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.2=he6710b0_1
  - matplotlib-base=3.3.0=py36h5ffbc53_1
  - mkl=2020.1=217
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.1.0=py36h23d657b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.4=py_1
  - ninja=1.10.0=py36hfd86e86_0
  - numpy=1.18.5=py36ha1c710e_0
  - numpy-base=1.18.5=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - openssl=1.1.1g=h516909a_1
  - pathlib=1.0.1=py36h9f0ad1d_2
  - pillow=7.2.0=py36hb39fc2d_0
  - pip=20.1.1=py36_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.6.10=h7579374_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.6.0=py3.6_cuda10.2.89_cudnn7.6.5_0
  - pywavelets=1.1.1=py36h785e9b2_1
  - readline=8.0=h7b6447c_0
  - scikit-image=0.17.2=py36h830a2c2_1
  - scipy=1.5.0=py36h0b6359f_0
  - setuptools=49.2.0=py36_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h62c20be_0
  - tifffile=2019.7.26.2=py36_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.10.0=py_0
  - torchvision=0.7.0=py36_cu102
  - tornado=6.0.4=py36h8c4c3a4_1
  - wheel=0.34.2=py36_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - antlr4-python3-runtime==4.8
    - dataclasses==0.7
    - hydra-core==1.0.0rc2
    - importlib-resources==3.0.0
    - omegaconf==2.0.1rc11
    - pyyaml==5.3.1
    - typing-extensions==3.7.4.2
    - zipp==3.1.0
prefix: /home/tanmayg/miniconda3/envs/gpv

